# /$$$$$$            /$$$$$$  /$$$$$$$   /$$$$$$  /$$                   /$$
#  |_  $$_/           /$$__  $$| $$__  $$ /$$__  $$| $$                  | $$
#    | $$   /$$$$$$$ | $$  \__/| $$  \ $$| $$  \__/| $$$$$$$   /$$$$$$  /$$$$$$
#    | $$  | $$__  $$| $$$$    | $$$$$$$ | $$      | $$__  $$ |____  $$|_  $$_/
#    | $$  | $$  \ $$| $$_/    | $$__  $$| $$      | $$  \ $$  /$$$$$$$  | $$
#    | $$  | $$  | $$| $$      | $$  \ $$| $$    $$| $$  | $$ /$$__  $$  | $$ /$$
#    /$$$$$$| $$  | $$| $$      | $$$$$$$/|  $$$$$$/| $$  | $$|  $$$$$$$  |  $$$$/
#   |______/|__/  |__/|__/      |_______/  \______/ |__/  |__/ \_______/   \___/
#                       =>InfiniteBungeeChat<=
# Servers Will Display As Glist
servers:
  lobby:
    max-players: 50

AntiSpam:
  chat_cooldown: 5 # Cooldown time in seconds


MOTD:
  enabled: false
  message: "&aWelcome to the &bServerName&a! Have a great time!"
  server: "lobby"